export const URLANALYTICS_REQUEST = 'URLANALYTICS_REQUEST';
export const URLANALYTICS_SUCCESS = 'URLANALYTICS_SUCCESS';
export const URLANALYTICS_FAIL = 'URLANALYTICS_FAIL';

export const URLLINKS_REQUEST = 'URLLINKS_REQUEST';
export const URLLINKS_SUCCESS = 'URLLINKS_SUCCESS';
export const URLLINKS_FAIL = 'URLLINKS_FAIL';

export const NEW_URLLINK_REQUEST = 'NEW_URLLINK_REQUEST';
export const NEW_URLLINK_SUCCESS = 'NEW_URLLINK_SUCCESS';
export const NEW_URLLINK_FAIL = 'NEW_URLLINK_FAIL';
export const NEW_URLLINK_RESET = 'NEW_URLLINK_RESET';

export const CREATE_CUSTOMLINK_REQUEST = 'CREATE_CUSTOMLINK_REQUEST';
export const CREATE_CUSTOMLINK_SUCCESS = 'CREATE_CUSTOMLINK_SUCCESS';
export const CREATE_CUSTOMLINK_FAIL = 'CREATE_CUSTOMLINK_FAIL';
export const CREATE_CUSTOMLINK_RESET = 'CREATE_CUSTOMLINK_RESET';

export const GENERATE_QR_REQUEST = 'GENERATE_QR_REQUEST';
export const GENERATE_QR_SUCCESS = 'GENERATE_QR_SUCCESS';
export const GENERATE_QR_FAIL = 'GENERATE_QR_FAIL';
export const GENERATE_QR_RESET = 'GENERATE_QR_RESET';

export const DELETE_URLLINK_REQUEST = 'DELETE_URLLINK_REQUEST';
export const DELETE_URLLINK_SUCCESS = 'DELETE_URLLINK_SUCCESS';
export const DELETE_URLLINK_FAIL = 'DELETE_URLLINK_FAIL';
export const DELETE_URLLINK_RESET = 'DELETE_URLLINK_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
